defaults: &defaults
  working_directory: ~/circleci-deployment
  docker:
    - image: circleci/node:6.12.3

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/circleci-deployment
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: yarn install
      - run:
          name: Build
          command: yarn build-prod
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: yarn install
      - run:
          name: Lint
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: yarn install
      - run:
          name: Run Tests
          command: echo "No Tests"
  deploy-prod:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:1a:e9:ce:aa:c9:0b:e7:9a:85:d1:98:9b:62:f7:64"
      - run:
          name: Deploy Production
          command: ssh -o "StrictHostKeyChecking no" $SSHUSER@$PROD_SERVER "cd ~/2tickets4me-redeem; git checkout master; git reset --hard origin/master; git pull origin master; yarn; yarn build-prod; yarn restart;"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - lint:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
      - deploy-prod:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
