version: 2
jobs:
  build:
    working_directory: ~/2tickets4me-redeem
    docker:
      - image: circleci/node:6.12.3
    steps:
      - checkout
      - restore_cache:
          key: 2tix-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: 2tix-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build-prod
  test:
    working_directory: ~/2tickets4me-redeem
    docker:
      - image: circleci/node:6.12.3
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run Tests
          command: echo "No Tests"
  deploy-prod:
    docker:
      - image: circleci/node:6.12.3
    working_directory: ~/2tickets4me-redeem
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:1a:e9:ce:aa:c9:0b:e7:9a:85:d1:98:9b:62:f7:64"
      - run:
          name: Deploy Production
          command: ssh -o "StrictHostKeyChecking no" $SSHUSER@$PROD_SERVER "cd ~/2tickets4me-redeem; git checkout master; git reset --hard origin/master; git pull origin master; yarn; yarn build-prod; yarn restart;"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy-prod:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: master
